/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SIpriv (https://sketchfab.com/S1Priv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-f14-tomcat-e99d03987b574e80971c1c8cc2b75925
Title: Low poly F14 Tomcat
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import f14 from '../assets/3d/low_poly_f14_tomcat.glb'
import { useFrame } from '@react-three/fiber'

const FighterJet = (props) =>{
  const jetRef = useRef()
  const { nodes, materials, animations } = useGLTF(f14)
  const { actions } = useAnimations(animations, jetRef)
 
  // useEffect(()=>{
  //   actions['animation tmct']?.play()
  // },[])
   useFrame(({clock,camera})=>{
     
     jetRef.current.position.y = Math.sin(clock.elapsedTime)* 0.2 + 2;
     if(jetRef.current.position.x > camera.position.x + 10){
       jetRef.current.rotation.y = Math.PI
     }
     else if(jetRef.current.position.x < camera.position.x -10){
      jetRef.current.rotation.y = 0
     }
     if(jetRef.current.rotation.y ===0){
      jetRef.current.position.x +=0.03
      jetRef.current.position.z -=0.03
     }
     else{
      jetRef.current.position.x -=0.03
      jetRef.current.position.z ==0.03
     }
   })


  return (
    <group ref={jetRef} {...props} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_119">
                <group name="bone_66">
                  <group
                    name="cylinder_0"
                    position={[0, 0.788, 0.744]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="bone2_5">
                    <group
                      name="cuboid_1"
                      position={[0, 0.855, 0.808]}
                      rotation={[-0.009, 0, -0.131]}>
                      <mesh
                        name="Object_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_9.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cuboid_2"
                      position={[0, 0.855, 0.808]}
                      rotation={[-0.009, 0, 0.131]}>
                      <mesh
                        name="Object_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_11.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cuboid_3"
                      position={[0, 0.855, 0.808]}
                      rotation={[-0.009, 0, 0.131]}>
                      <mesh
                        name="Object_13"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_13.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group
                      name="cuboid_4"
                      position={[0, 0.855, 0.808]}
                      rotation={[-0.009, 0, -0.131]}>
                      <mesh
                        name="Object_15"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_15.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone3_11">
                    <group name="cuboid_6" position={[-0.25, 0.738, 1.875]}>
                      <mesh
                        name="Object_18"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_18.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_7" position={[0.25, 0.738, 1.875]}>
                      <mesh
                        name="Object_20"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_20.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="bone5_10">
                      <group
                        name="cylinder_8"
                        position={[0, 0.855, 0.789]}
                        rotation={[1.562, 0, 0]}>
                        <mesh
                          name="Object_23"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_23.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cylinder_9"
                        position={[0, 0.855, 0.789]}
                        rotation={[1.562, 0, 0]}>
                        <mesh
                          name="Object_25"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_25.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="bone6_13" position={[-0.481, 0.837, 1.844]}>
                    <group
                      name="cuboid_12"
                      position={[-0.009, 0.013, 0.025]}
                      rotation={[0.007, -0.127, 0.031]}>
                      <mesh
                        name="Object_28"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_28.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone7_16">
                    <group name="cuboid_14" position={[0, 0.855, 0.808]} rotation={[-0.009, 0, 0]}>
                      <mesh
                        name="Object_31"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_31.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_15" position={[0, 0.855, 0.808]} rotation={[-0.009, 0, 0]}>
                      <mesh
                        name="Object_33"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_33.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone8_19">
                    <group name="sphere_17" position={[0, 0.844, 0.412]}>
                      <mesh
                        name="Object_36"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_36.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="sphere_18" position={[0, 0.844, 0.412]}>
                      <mesh
                        name="Object_38"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_38.geometry}
                        material={materials.material_2}
                      />
                    </group>
                  </group>
                  <group name="bone9_22">
                    <group name="cuboid_20" position={[-0.313, 0.887, 2.813]}>
                      <mesh
                        name="Object_41"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_41.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_21" position={[0.313, 0.887, 2.813]}>
                      <mesh
                        name="Object_43"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_43.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone10_24">
                    <group name="cuboid_23" position={[0, 0.688, 2.125]}>
                      <mesh
                        name="Object_46"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_46.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone11_31">
                    <group name="cuboid_25" position={[0.25, 0.412, 2.2]}>
                      <mesh
                        name="Object_49"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_49.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_26" position={[-0.25, 0.412, 2.2]}>
                      <mesh
                        name="Object_51"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_51.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_27" position={[-0.188, 0.762, 1.938]}>
                      <mesh
                        name="Object_53"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_53.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_28" position={[-0.375, 0.762, 1.875]}>
                      <mesh
                        name="Object_55"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_55.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_29" position={[0.188, 0.762, 1.938]}>
                      <mesh
                        name="Object_57"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_57.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_30" position={[0.375, 0.762, 1.875]}>
                      <mesh
                        name="Object_59"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_59.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone4_33">
                    <group
                      name="cylinder_32"
                      position={[-0.313, 0.525, 1.544]}
                      rotation={[-Math.PI / 2, 0.218, 0]}>
                      <mesh
                        name="Object_62"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_62.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone12_39">
                    <group name="cuboid_34" position={[0, 0.45, 0.125]}>
                      <mesh
                        name="Object_65"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_65.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_35" position={[0, 0.431, 0.125]}>
                      <mesh
                        name="Object_67"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_67.geometry}
                        material={materials.material_3}
                      />
                    </group>
                    <group name="bone13_38">
                      <group
                        name="cylinder_36"
                        position={[-0.15, 0.756, 0.106]}
                        rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                          name="Object_70"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_70.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group
                        name="cylinder_37"
                        position={[-0.15, 0.756, 0.025]}
                        rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh
                          name="Object_72"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_72.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="bone14_42">
                    <group name="cuboid_40" position={[-0.475, 0.656, 1.337]}>
                      <mesh
                        name="Object_75"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_75.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_41" position={[0.475, 0.656, 1.337]}>
                      <mesh
                        name="Object_77"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_77.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="bone22_51">
                    <group name="cuboid_43">
                      <mesh
                        name="Object_80"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_80.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="cuboid_44">
                      <mesh
                        name="Object_82"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_82.geometry}
                        material={materials.material_0}
                      />
                    </group>
                    <group name="bone23_47">
                      <group name="cuboid_45">
                        <mesh
                          name="Object_85"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_85.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cuboid_46">
                        <mesh
                          name="Object_87"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_87.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="bone24_50">
                      <group name="cuboid_48">
                        <mesh
                          name="Object_90"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_90.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="cuboid_49">
                        <mesh
                          name="Object_92"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_92.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="bone34_59">
                    <group name="cuboid_52" position={[0, 0.881, 0.563]}>
                      <mesh
                        name="Object_95"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_95.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group name="cuboid_53" position={[0, 0.881, 0.363]}>
                      <mesh
                        name="Object_97"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_97.geometry}
                        material={materials.material_4}
                      />
                    </group>
                    <group name="bone35_58">
                      <group name="cuboid_54" position={[0, 0.731, 0.188]}>
                        <mesh
                          name="Object_100"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_100.geometry}
                          material={materials.material_4}
                        />
                      </group>
                      <group
                        name="cuboid_55"
                        position={[0.025, 0.857, 0.253]}
                        rotation={[0.436, 0, 0]}>
                        <mesh
                          name="Object_102"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_102.geometry}
                          material={materials.material_5}
                        />
                      </group>
                      <group
                        name="cuboid_56"
                        position={[0.006, 0.915, 0.209]}
                        rotation={[0.157, 0, 0]}>
                        <mesh
                          name="Object_104"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_104.geometry}
                          material={materials.material_6}
                        />
                      </group>
                      <group name="cuboid_57" position={[0, 0.731, 0.481]}>
                        <mesh
                          name="Object_106"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_106.geometry}
                          material={materials.material_4}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="bone36_63">
                    <group name="cuboid_60" position={[0, 0.156, -0.656]}>
                      <mesh
                        name="Object_109"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_109.geometry}
                        material={materials.material_7}
                      />
                    </group>
                    <group name="cuboid_61" position={[0, 0.156, -0.656]}>
                      <mesh
                        name="Object_111"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_111.geometry}
                        material={materials.material_7}
                      />
                    </group>
                  </group>
                  <group name="bone38_65" position={[0.481, 0.837, 1.844]}>
                    <group
                      name="cuboid_64"
                      position={[0.009, 0.013, 0.025]}
                      rotation={[0.007, 0.127, -0.031]}>
                      <mesh
                        name="Object_114"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_114.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                </group>
                <group name="bone15_68">
                  <group name="cuboid_67" position={[-0.488, 0.619, 1.6]}>
                    <mesh
                      name="Object_117"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_117.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name="bone16_70">
                  <group name="cuboid_69" position={[0.488, 0.619, 1.6]}>
                    <mesh
                      name="Object_120"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_120.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name="bone17_72" position={[0.098, 0.66, 0.412]}>
                  <group name="cuboid_71" position={[-0.001, 0.003, 0]} rotation={[0, 0, 0.436]}>
                    <mesh
                      name="Object_123"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_123.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name="bone18_74" position={[-0.104, 0.66, 0.412]}>
                  <group name="cuboid_73" position={[0.007, 0.003, 0]} rotation={[0, 0, -0.436]}>
                    <mesh
                      name="Object_126"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_126.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name="bone19_80" position={[0, 0.705, 0.585]}>
                  <group name="cylinder_75" position={[0, -0.065, -0.057]} rotation={[0.218, 0, 0]}>
                    <mesh
                      name="Object_129"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_129.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group name="cylinder_76" position={[0, -0.065, -0.057]} rotation={[0.218, 0, 0]}>
                    <mesh
                      name="Object_131"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_131.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_77"
                    position={[0, -0.065, -0.057]}
                    rotation={[-0.567, 0, 0]}>
                    <mesh
                      name="Object_133"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_133.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_78"
                    position={[0.031, -0.268, -0.066]}
                    rotation={[0, 0, -Math.PI / 2]}>
                    <mesh
                      name="Object_135"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_135.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_79"
                    position={[-0.031, -0.268, -0.066]}
                    rotation={[0, 0, Math.PI / 2]}>
                    <mesh
                      name="Object_137"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_137.geometry}
                      material={materials.material_8}
                    />
                  </group>
                </group>
                <group name="bone20_94" position={[0, 0.792, 1.741]}>
                  <group name="cylinder_81" position={[-0.438, -0.007, -0.018]}>
                    <mesh
                      name="Object_140"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_140.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_82"
                    position={[-0.438, -0.007, -0.018]}
                    rotation={[-0.698, 0, 0]}>
                    <mesh
                      name="Object_142"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_142.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group name="cylinder_83" position={[-0.438, -0.007, -0.018]}>
                    <mesh
                      name="Object_144"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_144.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group name="cylinder_84" position={[-0.438, -0.007, -0.018]}>
                    <mesh
                      name="Object_146"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_146.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_85"
                    position={[-0.031, -0.354, -1.16]}
                    rotation={[0, 0, Math.PI / 2]}>
                    <mesh
                      name="Object_148"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_148.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_86"
                    position={[0, -0.792, -1.678]}
                    rotation={[-0.044, 0, 0]}>
                    <mesh
                      name="Object_150"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_150.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group name="cylinder_87" position={[0.438, -0.007, -0.018]}>
                    <mesh
                      name="Object_152"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_152.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_88"
                    position={[0.438, -0.007, -0.018]}
                    rotation={[-0.698, 0, 0]}>
                    <mesh
                      name="Object_154"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_154.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group name="cylinder_89" position={[0.438, -0.007, -0.018]}>
                    <mesh
                      name="Object_156"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_156.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_90"
                    position={[0.031, -0.354, -1.16]}
                    rotation={[0, 0, -Math.PI / 2]}>
                    <mesh
                      name="Object_158"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_158.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group name="cylinder_91" position={[0.438, -0.007, -0.018]}>
                    <mesh
                      name="Object_160"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_160.geometry}
                      material={materials.material_8}
                    />
                  </group>
                  <group
                    name="cylinder_92"
                    position={[0, -0.792, -1.678]}
                    rotation={[-0.044, 0, 0]}>
                    <mesh
                      name="Object_162"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_162.geometry}
                      material={materials.material_8}
                    />
                  </group>
                </group>
                <group name="bone25_97">
                  <group
                    name="cylinder_95"
                    position={[0.075, 0.531, 1.265]}
                    rotation={[-Math.PI / 2, -0.829, 0]}>
                    <mesh
                      name="Object_165"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_165.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group
                    name="cylinder_96"
                    position={[-0.075, 0.531, 1.265]}
                    rotation={[-Math.PI / 2, 0.829, 0]}>
                    <mesh
                      name="Object_167"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_167.geometry}
                      material={materials.material_3}
                    />
                  </group>
                </group>
                <group name="bone26_103">
                  <group
                    name="cylinder_98"
                    position={[-0.563, 0.731, 1.806]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_170"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_170.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group
                    name="cylinder_99"
                    position={[0.563, 0.731, 1.806]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_172"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_172.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group name="bone27_102" position={[-0.063, 0.156, 0]}>
                    <group
                      name="cylinder_100"
                      position={[-0.481, 0.594, 1.781]}
                      rotation={[-Math.PI / 2, 0, 0]}>
                      <mesh
                        name="Object_175"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_175.geometry}
                        material={materials.material_3}
                      />
                    </group>
                    <group
                      name="cylinder_101"
                      position={[0.606, 0.594, 1.781]}
                      rotation={[-Math.PI / 2, 0, 0]}>
                      <mesh
                        name="Object_177"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_177.geometry}
                        material={materials.material_3}
                      />
                    </group>
                  </group>
                </group>
                <group name="bone30_106" position={[-0.019, 0.175, -0.063]}>
                  <group
                    name="cylinder_104"
                    position={[-0.563, 0.575, 1.844]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_180"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_180.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group
                    name="cylinder_105"
                    position={[0.6, 0.575, 1.844]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_182"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_182.geometry}
                      material={materials.material_3}
                    />
                  </group>
                </group>
                <group name="bone28_109" position={[-0.019, 0.138, -0.063]}>
                  <group
                    name="cylinder_107"
                    position={[-0.563, 0.575, 1.844]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_185"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_185.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group
                    name="cylinder_108"
                    position={[0.6, 0.575, 1.844]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_187"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_187.geometry}
                      material={materials.material_3}
                    />
                  </group>
                </group>
                <group name="bone29_112" position={[0.019, 0.138, -0.063]}>
                  <group
                    name="cylinder_110"
                    position={[-0.563, 0.575, 1.844]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_190"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_190.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group
                    name="cylinder_111"
                    position={[0.525, 0.575, 1.844]}
                    rotation={[-Math.PI / 2, 0, 0]}>
                    <mesh
                      name="Object_192"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_192.geometry}
                      material={materials.material_3}
                    />
                  </group>
                </group>
                <group name="bone31_115">
                  <group
                    name="cylinder_113"
                    position={[-0.081, 0.531, 2.015]}
                    rotation={[-Math.PI / 2, 0.829, 0]}>
                    <mesh
                      name="Object_195"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_195.geometry}
                      material={materials.material_3}
                    />
                  </group>
                  <group
                    name="cylinder_114"
                    position={[0.081, 0.531, 2.015]}
                    rotation={[-Math.PI / 2, 0.829, 0]}>
                    <mesh
                      name="Object_197"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_197.geometry}
                      material={materials.material_3}
                    />
                  </group>
                </group>
                <group name="bone33_118">
                  <group
                    name="cylinder_117"
                    position={[0.313, 0.525, 1.544]}
                    rotation={[-Math.PI / 2, -0.218, 0]}>
                    <mesh
                      name="Object_200"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_200.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default FighterJet;



/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nortenko Dmytro (https://sketchfab.com/leondp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shahed-131-special-edition-black-1-c5efd7448f96445ea2242479ac161795
Title: Shahed-131 special edition (black 1)
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import Blackbirdjet from '../assets/3d/blackbirdjet.glb'

// const FighterJet = (props) =>{
//   const { nodes, materials } = useGLTF(Blackbirdjet)

//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['SHAHED-131-1_SHAHED-131-1_0'].geometry}
//         material={materials['SHAHED-131-1']}
//         scale={0.01}
//       />
//     </group>
//   )
// }

// export default FighterJet;
