/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Green Screen Direct (https://sketchfab.com/GSD_Official)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/luffy-gear-5-6475927ca55f4292977fd0f89be4ba8d
Title: Luffy Gear 5
*/

import React, { act, useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import Gear5Scene from '../assets/3d/luffy_gear_5.glb'

const Gear5Luffy =  ({currentAnimation,...props}) => {
  const gear5Ref = useRef()
  const { nodes, materials, animations } = useGLTF(Gear5Scene)
  const { actions } = useAnimations(animations, gear5Ref)


 useEffect(()=>{
    Object.values(actions).forEach(act=> act.stop())
    if(actions[currentAnimation]){
           actions[currentAnimation].play()
    }
 },[actions,currentAnimation])
  return (
    <group ref={gear5Ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="LuffyGear5fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={0.48}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_86"
                      geometry={nodes.Object_86.geometry}
                      material={materials.Material__26}
                      skeleton={nodes.Object_86.skeleton}
                    />
                    <skinnedMesh
                      name="Object_88"
                      geometry={nodes.Object_88.geometry}
                      material={materials['Material.001']}
                      skeleton={nodes.Object_88.skeleton}
                    />
                    <skinnedMesh
                      name="Object_90"
                      geometry={nodes.Object_90.geometry}
                      material={materials.Material__30}
                      skeleton={nodes.Object_90.skeleton}
                    />
                    <skinnedMesh
                      name="Object_92"
                      geometry={nodes.Object_92.geometry}
                      material={materials.Material__42}
                      skeleton={nodes.Object_92.skeleton}
                    />
                    <skinnedMesh
                      name="Object_94"
                      geometry={nodes.Object_94.geometry}
                      material={materials.Material__46}
                      skeleton={nodes.Object_94.skeleton}
                    />
                    <skinnedMesh
                      name="Object_96"
                      geometry={nodes.Object_96.geometry}
                      material={materials['Material__38.001']}
                      skeleton={nodes.Object_96.skeleton}
                    />
                    <skinnedMesh
                      name="Object_98"
                      geometry={nodes.Object_98.geometry}
                      material={materials.Material__35}
                      skeleton={nodes.Object_98.skeleton}
                    />
                    <skinnedMesh
                      name="Object_100"
                      geometry={nodes.Object_100.geometry}
                      material={materials.Material__27}
                      skeleton={nodes.Object_100.skeleton}
                    />
                    <skinnedMesh
                      name="Object_102"
                      geometry={nodes.Object_102.geometry}
                      material={materials.Material__31}
                      skeleton={nodes.Object_102.skeleton}
                    />
                    <skinnedMesh
                      name="Object_104"
                      geometry={nodes.Object_104.geometry}
                      material={materials.Material__43}
                      skeleton={nodes.Object_104.skeleton}
                    />
                    <skinnedMesh
                      name="Object_106"
                      geometry={nodes.Object_106.geometry}
                      material={materials['Material.001']}
                      skeleton={nodes.Object_106.skeleton}
                    />
                    <skinnedMesh
                      name="Object_108"
                      geometry={nodes.Object_108.geometry}
                      material={materials.Material__40}
                      skeleton={nodes.Object_108.skeleton}
                    />
                    <skinnedMesh
                      name="Object_110"
                      geometry={nodes.Object_110.geometry}
                      material={materials['Material__38.001']}
                      skeleton={nodes.Object_110.skeleton}
                    />
                    <skinnedMesh
                      name="Object_112"
                      geometry={nodes.Object_112.geometry}
                      material={materials.MI_chr0060_eye}
                      skeleton={nodes.Object_112.skeleton}
                    />
                    <skinnedMesh
                      name="Object_114"
                      geometry={nodes.Object_114.geometry}
                      material={materials.Material__32}
                      skeleton={nodes.Object_114.skeleton}
                    />
                    <skinnedMesh
                      name="Object_116"
                      geometry={nodes.Object_116.geometry}
                      material={materials.Material__44}
                      skeleton={nodes.Object_116.skeleton}
                    />
                    <skinnedMesh
                      name="Object_118"
                      geometry={nodes.Object_118.geometry}
                      material={materials.Material__25}
                      skeleton={nodes.Object_118.skeleton}
                    />
                    <skinnedMesh
                      name="Object_120"
                      geometry={nodes.Object_120.geometry}
                      material={materials.Material__34}
                      skeleton={nodes.Object_120.skeleton}
                    />
                    <skinnedMesh
                      name="Object_121"
                      geometry={nodes.Object_121.geometry}
                      material={materials.Material__33}
                      skeleton={nodes.Object_121.skeleton}
                    />
                    <skinnedMesh
                      name="Object_122"
                      geometry={nodes.Object_122.geometry}
                      material={materials.Material__35}
                      skeleton={nodes.Object_122.skeleton}
                    />
                    <skinnedMesh
                      name="Object_124"
                      geometry={nodes.Object_124.geometry}
                      material={materials.Material__29}
                      skeleton={nodes.Object_124.skeleton}
                    />
                    <skinnedMesh
                      name="Object_126"
                      geometry={nodes.Object_126.geometry}
                      material={materials.Material__41}
                      skeleton={nodes.Object_126.skeleton}
                    />
                    <skinnedMesh
                      name="Object_128"
                      geometry={nodes.Object_128.geometry}
                      material={materials.Material__45}
                      skeleton={nodes.Object_128.skeleton}
                    />
                    <group
                      name="Object_85"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_87"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_89"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_91"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_93"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_95"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_97"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_99"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_101"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_103"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_105"
                      position={[-17.463, 964.006, -31.081]}
                      rotation={[Math.PI, 0, 0]}
                      scale={9.905}
                    />
                    <group
                      name="Object_107"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_109"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_111"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_113"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_115"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_117"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_119"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_123"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_125"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                    <group
                      name="Object_127"
                      position={[-2.952, -35.402, 1.525]}
                      rotation={[Math.PI, 0, 0]}
                      scale={8.45}
                    />
                  </group>
                </group>
                <group
                  name="Object_4"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_14"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_8"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_20"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_24"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_16"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_13001"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_5_1"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_9"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_21"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_6"
                  position={[-17.463, 964.006, -31.081]}
                  rotation={[Math.PI, 0, 0]}
                  scale={9.905}
                />
                <group
                  name="Object_18"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_14001"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_2_1"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_10"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_22"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_3"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_12"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_7"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_19"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
                <group
                  name="Object_23"
                  position={[-2.952, -35.402, 1.525]}
                  rotation={[Math.PI, 0, 0]}
                  scale={8.45}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Gear5Luffy;