/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Cameraman (https://sketchfab.com/wannoischool01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/godzilla-2014-kiss-of-death-1283c3c1ca914ef1bc407a9f28d624bc
Title: Godzilla 2014 - Kiss Of Death
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import GodZillaScene from '../assets/3d/godzilla_2014_-_kiss_of_death.glb'

const GodZilla =(props)=> {
  const group = useRef()
  const {scene, nodes, materials, animations } = useGLTF(GodZillaScene,true, 'https://www.gstatic.com/draco/v1/decoders/')
  const { actions } = useAnimations(animations, group)
  
  useEffect(()=>{
    if(actions){
      Object.values(actions).forEach(act => act.stop())
        setTimeout(()=>{
            actions['Animation']?.play()
        },5000)       
    }
  },[])

  return (
    <group ref={group} {...props} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Godzilla_2014_35_130">
                <group name="Godzilla_2014_35_arm_100">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_8"
                      geometry={nodes.Object_8.geometry}
                      material={materials.material}
                      skeleton={nodes.Object_8.skeleton}
                    />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.material_1}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.material_2}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name="Object_11"
                      geometry={nodes.Object_11.geometry}
                      material={materials.material_3}
                      skeleton={nodes.Object_11.skeleton}
                    />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.material_4}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <group name="Godzilla_2014_35_mesh_99" />
                  </group>
                </group>
              </group>
              <group name="000_head_131" position={[0.616, 210.31, 64]} rotation={[1.728, 0, 0]}>
                <mesh
                  name="Object_111"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_111.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group
                name="001_arm_R_132"
                position={[-32.441, 168.368, 40.233]}
                rotation={[0, 0, -1.503]}>
                <mesh
                  name="Object_113"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_113.geometry}
                  material={materials.mmd_tools_rigid_1}
                />
              </group>
              <group
                name="002_arm_L_133"
                position={[32.441, 168.368, 40.233]}
                rotation={[0, 0, 1.504]}>
                <mesh
                  name="Object_115"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_115.geometry}
                  material={materials.mmd_tools_rigid_2}
                />
              </group>
              <group
                name="003_elbow_R_134"
                position={[-58.062, 166.359, 41.689]}
                rotation={[0, 0, -1.414]}>
                <mesh
                  name="Object_117"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_117.geometry}
                  material={materials.mmd_tools_rigid_1}
                />
              </group>
              <group
                name="004_elbow_L_135"
                position={[58.062, 166.359, 41.689]}
                rotation={[0, 0, 1.414]}>
                <mesh
                  name="Object_119"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_119.geometry}
                  material={materials.mmd_tools_rigid_2}
                />
              </group>
              <group
                name="005_leg1_R_136"
                position={[-28.287, 101.389, -1.554]}
                rotation={[-0.443, 0, -0.091]}>
                <mesh
                  name="Object_121"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_121.geometry}
                  material={materials.mmd_tools_rigid_7}
                />
              </group>
              <group
                name="006_leg2_R_137"
                position={[-28.287, 105.387, -3.169]}
                rotation={[-0.443, 0, 0.021]}>
                <mesh
                  name="Object_123"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_123.geometry}
                  material={materials.mmd_tools_rigid_7}
                />
              </group>
              <group
                name="007_leg1_L_138"
                position={[28.287, 101.389, -1.554]}
                rotation={[-0.443, 0, 0.091]}>
                <mesh
                  name="Object_125"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_125.geometry}
                  material={materials.mmd_tools_rigid_7}
                />
              </group>
              <group
                name="008_leg2_L_139"
                position={[28.287, 105.387, -3.169]}
                rotation={[-0.443, 0, -0.021]}>
                <mesh
                  name="Object_127"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_127.geometry}
                  material={materials.mmd_tools_rigid_7}
                />
              </group>
              <group
                name="009_knee_R_140"
                position={[-30.855, 47.127, 11.749]}
                rotation={[0.192, 0, 0.03]}>
                <mesh
                  name="Object_129"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_129.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group
                name="00A_knee_L_141"
                position={[30.855, 47.127, 11.749]}
                rotation={[0.192, 0, -0.03]}>
                <mesh
                  name="Object_131"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_131.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group
                name="00B_u_body1_142"
                position={[-1.848, 143.715, 7.876]}
                rotation={[-0.279, 0, 0.087]}>
                <mesh
                  name="Object_133"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_133.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group
                name="00C_u_body2_143"
                position={[1.848, 143.715, 7.876]}
                rotation={[-0.279, 0, -0.087]}>
                <mesh
                  name="Object_135"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_135.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group name="00D_u_body3_144" position={[-2.464, 143.715, 10.956]}>
                <mesh
                  name="Object_137"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_137.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group name="00E_u_body4_145" position={[2.464, 143.715, 10.956]}>
                <mesh
                  name="Object_139"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_139.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group name="00F_l_body_146" position={[0, 127.773, 8.475]} rotation={[-0.18, 0, 0]}>
                <mesh
                  name="Object_141"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_141.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group
                name="00G_chin_147"
                position={[0, 200.506, 75.209]}
                rotation={[0.157, 0, 1.57]}>
                <mesh
                  name="Object_143"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_143.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group name="00H_neck_148" position={[0, 191.807, 42.506]} rotation={[0.609, 0, 0]}>
                <mesh
                  name="Object_145"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_145.geometry}
                  material={materials.mmd_tools_rigid_0}
                />
              </group>
              <group
                name="Female_Muto_30_Accurate_249"
                position={[4.171, -37.843, 92.916]}
                rotation={[-2.973, 0.022, -3.088]}>
                <group name="Female_Muto_30_Accurate_arm_248">
                  <group name="GLTF_created_1">
                    <primitive object={nodes.GLTF_created_1_rootJoint} />
                    <skinnedMesh
                      name="Object_151"
                      geometry={nodes.Object_151.geometry}
                      material={materials.material_9}
                      skeleton={nodes.Object_151.skeleton}
                    />
                    <group name="Female_Muto_30_Accurate_mesh_247" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default GodZilla;
