/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LivindorCreation (https://sketchfab.com/LivindorCreation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/magic-forest-dragon-9e1bcd17aa0f441fbf204fdfc7b8d8f7
Title: Magic Forest Dragon
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
 import MonsterScene from '../assets/3d//magic_forest_dragon.glb'

const Monster =({playSequence,currentAnimation ,...props}) => {
  const monsterRef = useRef()
  const { nodes, materials, animations } = useGLTF(MonsterScene,true, 'https://www.gstatic.com/draco/v1/decoders/')
  const { actions } = useAnimations(animations, monsterRef)
  
  useEffect(()=>{
    // initially disable all actions and only act on them on necessary features
    Object.values(actions).forEach((action)=> action.stop())
    if(actions[currentAnimation]){
      actions[currentAnimation].play()
    }
  },[actions,currentAnimation])
  return (
    <group ref={monsterRef} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={8.28}>
          <group name="Magic_Forest_Dragonfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Mob_magicforest_jade_dragon}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Object_6" />
                  <group name="Mob_magicforest_jade_dragon" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Monster;
