/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hatch-naruto-1f2c51af4c5c43fe941b4342ea6bbc4a
Title: Hatch Naruto
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import NarutoScene from '../assets/3d/hatch_naruto.glb'
import { a} from '@react-spring/three'

const Naruto =({currentAnimation} ,...props) =>{
  
  const narutoRef = useRef()
  const { nodes, materials, animations } = useGLTF(NarutoScene)
  const { actions } = useAnimations(animations, narutoRef)
  
  const adjustNarutoScreen = ()=>{
    let screenScale=[2.5,2.5,2.5], screenPosition=[0,-2.2,0.1]
      if(window.innerWidth < 450) {
       screenScale = [17, 17, 17];
       screenPosition = [0, -17.5, -30.4];
      }
     else if (window.innerWidth < 769 & window.innerWidth>450) {
       screenScale = [17, 17, 17];
       screenPosition = [0, -17.5, -30.4];
     } else {
      screenScale = [17, 17, 17];
      screenPosition = [0, -17.5, -30.4];
     }     
     return [screenPosition,screenScale];       
 }

 const [position , scale] = adjustNarutoScreen()

  useEffect(()=>{
    Object.values(actions).forEach(act=> act.stop())
    if(actions[currentAnimation]){
        actions[currentAnimation].play()
    }
  },[actions,currentAnimation ])
  return (
      <a.group ref={narutoRef} position={position} rotation={[12.6,-0.1,0]} scale={scale}   {...props} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.C__Users_JK_Desktop_NARUTO_ULTI}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.C__Users_JK_Desktop_NARUTO_ULTI0}
                    skeleton={nodes.Object_8.skeleton}
                  />
                  <group name="Object_6" />
                  <group name="Bandage_Naruto_obj" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  )
}

export default Naruto